.PHONY: run
run:
	@echo
	@echo
	@echo "-----------------------------------------------------"
	@echo "                       DEMO"
	@echo "-----------------------------------------------------"
	@echo "Modify the files under files to trigger the commands."
	@echo "Command #1 will run for all files."
	@echo "Command #2 will run for all files except file00.txt."
	@echo "-----------------------------------------------------"
	@echo
	@echo
	node ../../index.js watch.config.json
